# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyWeather

 pod 'Moya', '~> 13.0'
 pod 'Alamofire', '~> 4.8.2'
 pod 'PromiseKit'
 pod 'Bond'
 pod 'SnapKit'
 pod 'FirebaseCore'
 pod 'FirebaseFirestore'
 pod 'FirebaseCrashlytics'
 


end
